"""
Django settings for pelican_publisher project.

Generated by 'django-admin startproject' using Django 3.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import warnings
from json.decoder import JSONDecodeError
from logging import getLogger
from pathlib import Path

from dataclass_wizard import DataclassWizard
from django_vises.deploy.deploy_stage import DeployStage
from django_vises.django_settings.helpers import parser_database_uri

from pelican_publisher import __version__
from pelican_publisher.sentry import init_sentry

from .ev import EV

logger = getLogger("__file__")

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = EV.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = EV.DEBUG

ALLOWED_HOSTS = EV.ALLOWED_HOSTS

# Application definition

INSTALLED_APPS = [
    # "django.contrib.admin",
    # "django.contrib.auth",
    # "django.contrib.contenttypes",
    # "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "tailwind",
    "pelican_publisher.core",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    # "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "pelican_publisher.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "pelican_publisher.wsgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {"default": parser_database_uri(EV.DATABASE_URI, base_dir=BASE_DIR)}


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = EV.TZ
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR.joinpath("pelican_publisher", "staticfiles")


# https://github.com/RealOrangeOne/django-tasks
TASKS = {
    "default": {
        "BACKEND": "django.tasks.backends.immediate.ImmediateBackend",
    }
}


# Pelican Publisher
class PelicanSite(DataclassWizard):
    NAME: str
    ZIP_URL: str
    WEBHOOK_SECRET: str


def _parse_pelican_sites(data: str) -> list[PelicanSite]:
    try:
        result = PelicanSite.from_json(data)

    except (ValueError, JSONDecodeError) as e:
        raise Exception(f"please check ENV: PELICAN_SITES. {e}")

    if not isinstance(result, list):
        raise Exception("please check ENV: PELICAN_SITES")

    return result


if len(EV.PELICAN_SITES) == 0:
    logger.warning("please set ENV: PELICAN_SITES")
else:
    PELICAN_SITES = _parse_pelican_sites(EV.PELICAN_SITES)


# Sentry
if EV.SENTRY_DSN:
    from sentry_sdk.integrations.asyncio import AsyncioIntegration
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.integrations.logging import LoggingIntegration

    init_sentry(
        dsn=EV.SENTRY_DSN,
        integrations=[AsyncioIntegration(), DjangoIntegration(), LoggingIntegration()],
        app_name="PelicanPublisher",
        app_version=__version__,
        user_id_is_mac_address=True,
    )


# 基于部署环境调整 ---
# --- 多环境共享
if EV.DEPLOY_STAGE in (DeployStage.LOCAL, DeployStage.DEV):
    # 打开调试信息
    DEBUG = True
    warnings.simplefilter("always", DeprecationWarning)
    warnings.simplefilter("always", FutureWarning)

    # 模版调试
    TEMPLATES[0]["OPTIONS"]["context_processors"].insert(
        0, "django.template.context_processors.debug"
    )

    # 测试部署环境
    ALLOWED_HOSTS = ["*"]
    INTERNAL_IPS = ("127.0.0.1",)


# --- 环境之间独立
match EV.DEPLOY_STAGE:
    case DeployStage.LOCAL:
        # 避免再登录
        SECRET_KEY = "e375cf18ebbf40259c96696671bbb7a1"

        # debug 工具
        INSTALLED_APPS += [
            "django.contrib.auth",
            "django.contrib.contenttypes",
            "orbit",
        ]
        MIDDLEWARE.insert(0, "orbit.middleware.OrbitMiddleware")

    case DeployStage.DEV:
        # USE_X_FORWARDED_HOST = True
        pass

    case DeployStage.PRD:
        pass
