# Generated by Django 6.0.2 on 2026-02-07 14:14

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("created_time", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("site_name", models.CharField()),
                ("status", models.CharField(default="READY")),
                ("stdout", models.TextField(null=True)),
                ("stderr", models.TextField(null=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
